import { describe, expect, it } from "vitest";
import corpus from "../eval/corpus/text.json";
import { buildTextResult, decideTextVerdict, type ModelOutcome, type TextModelOutput } from "@/lib/detect/text";
import { locateSentences, textPatterns } from "@/lib/detect/text-signals";
import type { ModelScore } from "@/lib/detect/types";

const meta = { id: "TEST", createdAt: "2026-01-01T00:00:00.000Z" };
const notConfigured: ModelOutcome<TextModelOutput> = { status: "not_configured", name: "GPTZero", message: "not set" };
const words = (n: number) => Array.from({ length: n }, (_, i) => `word${i % 50}`).join(" ") + ".";
const score = (ai: number, extra: Partial<ModelScore> = {}): ModelScore => ({ provider: "Test model", ai, mixed: null, human: null, confidence: null, ...extra });
const ok = (s: ModelScore, sentences: TextModelOutput["sentences"] = []): ModelOutcome<TextModelOutput> => ({ status: "ok", name: "Test model", output: { score: s, sentences } });

describe("text verdicts", () => {
  it("never scores or decides without a detection model, however AI-like the writing", () => {
    for (const item of corpus.items) {
      const r = buildTextResult(item.text, notConfigured, meta);
      expect(r.verdict, item.id).toBe("inconclusive");
      expect(r.score, item.id).toBeNull();
    }
  });

  it("treats short text as inconclusive and ignores any model score for it", () => {
    const r = buildTextResult(words(60), ok(score(0.99)), meta);
    expect(r.verdict).toBe("inconclusive");
    expect(r.score).toBeNull();
    expect(r.headline).toMatch(/too short/i);
    expect(r.checks[0]!.status).toBe("skipped");
  });

  it("reports a provider failure without inventing a score", () => {
    const r = buildTextResult(words(300), { status: "error", name: "GPTZero", message: "GPTZero returned an error (HTTP 500)" }, meta);
    expect(r.verdict).toBe("inconclusive");
    expect(r.score).toBeNull();
    expect(r.summary).toContain("HTTP 500");
  });

  it("uses conservative thresholds, stricter for shorter texts", () => {
    expect(decideTextVerdict(score(0.9), 300)).toBe("likely_ai");
    expect(decideTextVerdict(score(0.9), 150)).toBe("inconclusive");
    expect(decideTextVerdict(score(0.97), 150)).toBe("likely_ai");
    expect(decideTextVerdict(score(0.8), 400)).toBe("inconclusive");
    expect(decideTextVerdict(score(0.05, { human: 0.9, mixed: 0.05 }), 300)).toBe("likely_human");
    expect(decideTextVerdict(score(0.05, { human: 0.9, mixed: 0.05 }), 150)).toBe("inconclusive");
    expect(decideTextVerdict(score(0.2, { human: 0.1, mixed: 0.7 }), 300)).toBe("mixed");
    expect(decideTextVerdict(score(0.5, { human: 0.4, mixed: 0.1 }), 300)).toBe("inconclusive");
  });

  it("never decides when the model itself reports low confidence", () => {
    expect(decideTextVerdict(score(0.99, { confidence: "low" }), 400)).toBe("inconclusive");
    expect(decideTextVerdict(score(0.01, { human: 0.99, confidence: "low" }), 400)).toBe("inconclusive");
  });

  it("highlights the sentences the model scored as likely AI", () => {
    const text = "The first sentence is mine.  It was written by hand.\n\nThis second one, however, was generated by a model.";
    const padded = `${text} ${words(120)}`;
    const r = buildTextResult(
      padded,
      ok(score(0.6, { human: 0.3, mixed: 0.1 }), [
        { text: "The first sentence is mine.", ai: 0.1 },
        { text: "It was written by hand.", ai: 0.2 },
        { text: "This second one, however, was generated by a model.", ai: 0.93 },
      ]),
      meta,
    );
    const model = r.highlights.filter((h) => h.kind === "model");
    expect(model).toHaveLength(1);
    expect(padded.slice(model[0]!.start, model[0]!.end)).toBe("This second one, however, was generated by a model.");
    expect(model[0]!.ai).toBe(0.93);
  });

  it("always includes the African English fairness caveat", () => {
    const r = buildTextResult(words(300), ok(score(0.95)), meta);
    expect(r.caveats.join(" ")).toMatch(/African English/);
  });
});

describe("writing patterns", () => {
  it("locates provider sentences despite whitespace differences", () => {
    const text = "One  line\nhere. Second\tsentence!";
    const spans = locateSentences(text, ["One line here.", "Second sentence!", "Missing."]);
    expect(text.slice(spans[0]!.start, spans[0]!.end)).toBe("One  line\nhere.");
    expect(text.slice(spans[1]!.start, spans[1]!.end)).toBe("Second\tsentence!");
    expect(spans[2]).toBeNull();
  });

  it("flags pasted chatbot wording", () => {
    const item = corpus.items.find((i) => i.id === "ai-artifacts")!;
    const p = textPatterns(item.text);
    expect(p.evidence.find((e) => e.id === "artifacts")).toBeTruthy();
    expect(p.highlights.filter((h) => h.kind === "artifact").length).toBeGreaterThanOrEqual(3);
  });

  it("flags zero-width characters but not emoji joiners", () => {
    const item = corpus.items.find((i) => i.id === "human-plaatje-zero-width")!;
    expect(textPatterns(item.text).evidence.find((e) => e.id === "hidden")?.direction).toBe("warning");
    expect(textPatterns("Our team 👩‍💻 shipped it.").evidence.find((e) => e.id === "hidden")).toBeUndefined();
  });

  it("flags look-alike letters from other alphabets", () => {
    const p = textPatterns("This pаper was written by me."); // Cyrillic 'а'
    expect(p.highlights.some((h) => h.kind === "hidden")).toBe(true);
  });

  it("does not flag chatbot wording in ordinary human writing", () => {
    for (const item of corpus.items.filter((i) => i.label === "human")) {
      expect(textPatterns(item.text).evidence.find((e) => e.id === "artifacts"), item.id).toBeUndefined();
    }
  });
});
