import "server-only";
import { AlignmentType, BorderStyle, Document, HeadingLevel, Packer, Paragraph, ShadingType, Table, TableCell, TableRow, TextRun, WidthType } from "docx";

const FONT = "Calibri";

function paragraphsFrom(text: string): Paragraph[] {
  return text
    .split(/\n\s*\n/)
    .map((block) => block.trim())
    .filter(Boolean)
    .map((block) => {
      const md = /^(#{1,3})\s+(.*)$/.exec(block);
      if (md) {
        const level = [HeadingLevel.HEADING_1, HeadingLevel.HEADING_2, HeadingLevel.HEADING_3][md[1]!.length - 1];
        return new Paragraph({ heading: level, children: [new TextRun({ text: md[2]!, font: FONT })] });
      }
      const lines = block.split("\n");
      return new Paragraph({
        spacing: { after: 200, line: 300 },
        children: lines.flatMap((line, i) => [new TextRun({ text: line, font: FONT, size: 24, break: i > 0 ? 1 : 0 })]),
      });
    });
}

export async function documentDocx(title: string, text: string): Promise<Buffer> {
  const doc = new Document({
    creator: "PanPen (Tolbert Innovation Hub)",
    title,
    sections: [
      {
        children: [new Paragraph({ heading: HeadingLevel.TITLE, children: [new TextRun({ text: title, font: FONT })] }), ...paragraphsFrom(text)],
      },
    ],
  });
  return Packer.toBuffer(doc);
}

type ReportSegment = { original: string; final: string; risk: "none" | "low" | "medium" | "high"; notes: string[] };

const RISK_COLOUR: Record<ReportSegment["risk"], string> = { none: "E8F5E9", low: "FFF8E1", medium: "FFE0B2", high: "FFCDD2" };
const RISK_LABEL: Record<ReportSegment["risk"], string> = { none: "No concerns", low: "Minor — review", medium: "Check meaning", high: "Meaning may have changed" };

function cell(text: string, shade?: string) {
  return new TableCell({
    width: { size: 50, type: WidthType.PERCENTAGE },
    shading: shade ? { type: ShadingType.CLEAR, color: "auto", fill: shade } : undefined,
    margins: { top: 80, bottom: 80, left: 100, right: 100 },
    children: text.split("\n").map((t) => new Paragraph({ children: [new TextRun({ text: t, font: FONT, size: 20 })] })),
  });
}

/** A transparent side-by-side revision report suitable for supervisors or integrity reviews. */
export async function reportDocx(title: string, segments: ReportSegment[]): Promise<Buffer> {
  const flagged = segments.filter((s) => s.risk !== "none").length;
  const rows = segments.flatMap((s, i) => {
    const r = [
      new TableRow({
        children: [
          new TableCell({
            columnSpan: 2,
            shading: { type: ShadingType.CLEAR, color: "auto", fill: RISK_COLOUR[s.risk] },
            children: [
              new Paragraph({
                children: [
                  new TextRun({ text: `Paragraph ${i + 1} — ${RISK_LABEL[s.risk]}`, bold: true, font: FONT, size: 18 }),
                  ...s.notes.map((n) => new TextRun({ text: `• ${n}`, font: FONT, size: 18, break: 1 })),
                ],
              }),
            ],
          }),
        ],
      }),
      new TableRow({ children: [cell(s.original), cell(s.final)] }),
    ];
    return r;
  });
  const doc = new Document({
    creator: "PanPen (Tolbert Innovation Hub)",
    title: `${title} — revision report`,
    sections: [
      {
        children: [
          new Paragraph({ heading: HeadingLevel.TITLE, children: [new TextRun({ text: title, font: FONT })] }),
          new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text: "Revision report", font: FONT })] }),
          new Paragraph({
            spacing: { after: 200 },
            children: [
              new TextRun({
                text: `Generated by PanPen (powered by Tolbert Innovation Hub) on ${new Date().toUTCString()}. The author's text was edited for clarity and natural expression; citations, quotations and figures were protected from change. ${flagged} of ${segments.length} paragraphs were flagged for the author to review.`,
                font: FONT,
                size: 20,
              }),
            ],
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            borders: {
              top: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
              bottom: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
              left: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
              right: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
              insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
              insideVertical: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
            },
            rows: [
              new TableRow({
                tableHeader: true,
                children: ["Original", "Revised"].map(
                  (h) =>
                    new TableCell({
                      shading: { type: ShadingType.CLEAR, color: "auto", fill: "1F3D2B" },
                      children: [new Paragraph({ alignment: AlignmentType.LEFT, children: [new TextRun({ text: h, bold: true, color: "FFFFFF", font: FONT })] })],
                    }),
                ),
              }),
              ...rows,
            ],
          }),
        ],
      },
    ],
  });
  return Packer.toBuffer(doc);
}
